substitutions:
  device_name: enc8-minimal
  friendly_name: enc8-minimal
  sda_pin: "6"
  scl_pin: "7"

esphome:
  name: $device_name
  friendly_name: $friendly_name

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

external_components:
  - source: github://nonik0/esphome-m5stack-unit8encoder@main
    components: [m5stack_unit8encoder]

logger:
  #level: DEBUG # Uncomment this line for more verbose logging

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  sda: $sda_pin
  scl: $scl_pin
  
m5stack_unit8encoder:
  - id: unit8encoder

binary_sensor:
  - platform: m5stack_unit8encoder
    m5stack_unit8encoder_id: unit8encoder
    switch:
      id: switch
    button_1:
      id: button_1
    button_2:
      id: button_2
    button_3:
      id: button_3
    button_4:
      id: button_4
    button_5:
      id: button_5
    button_6:
      id: button_6
    button_7:
      id: button_7
    button_8:
      id: button_8

sensor:
  - platform: m5stack_unit8encoder
    m5stack_unit8encoder_id: unit8encoder
    encoder_1:
      id: delta_1
    encoder_2:
      id: delta_2
    encoder_3:
      id: delta_3
    encoder_4:
      id: delta_4
    encoder_5:
      id: delta_5
    encoder_6:
      id: delta_6
    encoder_7:
      id: delta_7
    encoder_8:
      id: delta_8

light:
  - platform: m5stack_unit8encoder
    m5stack_unit8encoder_id: unit8encoder
    led_1:
      id: led_1
    led_2:
      id: led_2
    led_3:
      id: led_3
    led_4:
      id: led_4
    led_5:
      id: led_5
    led_6:
      id: led_6
    led_7:
      id: led_7
    led_8:
      id: led_8